#!/bin/bash
host=$1
cmd="sudo python /usr/lib/python2.6/site-packages/ambari_agent/AmbariCleaner.py"

localUser="tencent"
loginUser="tencent"
loginPass="tencent"

sudo su ${localUser} -c "echo ../execRemoteCmd.exp ${host} ${loginUser} ${loginPass} 150 \"${cmd}\""
